[package]
name = "rust_dart_gen"
description = "A Dart code generator built using Rust"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
glob = "0.3.2"
regex = "1.11.1"
